using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppAssignmentDATABASE_5.Models
{
    public class Language
    {
        [Key]
        public int LanguageId { get; set; }

        [Required]
        [MaxLength(20)]
        [MinLength(1)]
        public string LanguageName { get; set; }

        
        public List<PersonLanguage> PersonKnownLaguageList { get; set; }  //List of People

        public Language(string LanguageName) //Id generated by Database so no need to add inside the constructor
        {
            this.LanguageName = LanguageName;
            PersonKnownLaguageList = new List<PersonLanguage>(); //going to return list of Languages from PersonLanguage class to PersonKnownLanguageList
        }


    }
}
